### ISSUE TITLE
Laundry list of more or less useful ideas

### ISSUE THREAD

**Issue by MordecaiMalignatus** [raylu/j4lp#1]
- Colour coding of entries, red for invalid fits, green for valid fits, colour the doctrine name only
- Better formatting, better readability, maybe monospaced font
- Adding payout amount for valid fits
- sorting newest -> oldest
- limiting the script to the last 50 things, maybe
- adding a (x days ago) per item

things that probably exceed the frame of the script: 
- Use of states for the individual killmails, i.e. ignoring green-set rows in the spreadsheet, automatically colouring bad fits red, colouring valid fits yellow just needing payout. 
  - payout statistics.

**Comment by raylu** [comment]
surprisingly, you can't read the color of a cell. i'm instead ignoring rows based on text in the "paid out by" column

you should check out the new formatting

i don't plan on showing 'days ago'. payout statistics should definitely be calculated in the spreadsheet itself

the only thing I haven't done is suggesting a payout amount
